apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ytdown
  namespace: ytdown
  annotations:
    # Dostosuj do swojego ingress controllera, np. nginx:
    # nginx.ingress.kubernetes.io/proxy-body-size: "0"
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
    - host: ytdown.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ytdown
                port:
                  name: http
  # tls:
  #   - hosts:
  #       - ytdown.example.com
  #     secretName: ytdown-tls
