apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ytdown

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  # - ingress.yaml   # odkomentuj jeśli używasz Ingress

images:
  - name: ghcr.io/OWNER/ytdown
    newName: ghcr.io/OWNER/ytdown
    newTag: latest
